[package]
name = "dotin"
version = "0.0.0"
edition = "2021"
description = "A simple dotfiles manager inspired by `stow`."

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
fs-err = { version = "2.9.0" }
fs-tree = { path = "/home/marcospb19/fs-tree" }

[dev-dependencies]
pretty_assertions = "1.4.0"
tempfile = "3.8.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
