[package]
name = "dotin"
version = "0.0.0"
edition = "2021"
description = "A simple dotfiles manager inspired by `stow`."

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
file_type_enum = "2.0.1"
fs-err = { version = "3.0.0" }
fs-tree = { version = "0.6.0", features = ["fs-err"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
tempfile = "3.8.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
